# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

components:
  parameters:
    locality_id:
      name: "locality_id"
      description: "Locality id of used to fetch neighbourhoods"
      in: path
      required: True
      schema:
        type: "integer"

paths:
  /placetypes:
    get:
      operationId: "shapefile.get_shapefiles"
      tags:
        - "Shapefiles"
      summary: "Read the list of placetypes"
      responses:
        "200":
          description: "Successfully read all placetypes"

  /neighbourhoods/{locality_id}:
    get:
      operationId: "shapefile.get_neighbourhoods_by_locality_id"
      tags:
        - Neighbourhoods
      parameters:
        - $ref: "#/components/parameters/locality_id"
      responses:
        "204":
          description: "Successfully pulled all neighbourhoods for neighbourhood"
        "205":
          description: "Locality ID incorrect, returning neighbourhoods for a random locality:D "