# swagger.yml

openapi: 3.0.0
info:
  title: "RP Flask REST API"
  description: "An API about people and notes"
  version: "1.0.0"

servers:
  - url: "/api"

paths:
  /neighbourhoods:
    get:
      operationId: "placetypes.read_all"
      tags:
        - "Placetypes"
      summary: "Read the list of placetypes"
      responses:
        "200":
          description: "Successfully read all placetypes"