datapath: "/Users/Shared/wofdata/data/"

reporting_markets:
  - Name: "Chicago"
    id: 85940195
  - Name: "New York"
    id: 85977539
  - Name: "Washington"
    id: 85931779
#  - Name: "Toronto"
#    id: 101735835
  - Name: "Boston"
    id: 85950361
  - Name: "Los Angeles"
    id: 85923517
  - Name: "Seattle"
    id: 101730401
  - Name: "San Fransisco"
    id: 85922583
    alt_shape: "alt-mapzen"
  - Miami:
    id: 85933669
